<div class="loader-wrapper">
         <div class="loader"> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200" height="200" style="shape-rendering: auto; display: block; background: transparent;"><g><g transform="rotate(0 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.5424063116370809s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(30 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.49309664694280075s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(60 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.4437869822485207s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(90 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.3944773175542406s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(120 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.34516765285996054s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(150 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.29585798816568043s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(180 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.24654832347140038s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(210 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.1972386587771203s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(240 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.14792899408284022s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(270 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.09861932938856015s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(300 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="-0.049309664694280074s" repeatCount="indefinite"/>
  </rect>
</g><g transform="rotate(330 50 50)">
  <rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#fe718d">
    <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="0.591715976331361s" begin="0s" repeatCount="indefinite"/>
  </rect>
</g><g/></g><!-- [ldio] generated by https://loading.io --></svg></div>
      </div>

<section class="hero-section">
  
      <div class="hero">
        <h2> Loja PHP</h2>
        <p>
          Uma loja criada em PHP com o objetivo de ensinar a programar em PHP para aprender mais sobre programação.
        </p>
        <div class="buttons">
          <a href="?a=login" class="login">Login</a>
          <a href="?a=novo_cliente" class="criarconta">Criar conta</a>
        </div>
      </div>
      <div class="img">
        <img src="https://cdn.discordapp.com/attachments/884520876324819038/1231038968217473134/6f1c0806e6eb16b6ff0659a41b20908a-topaz-denoise-enhance-4x-color.png?ex=66358161&is=66230c61&hm=28b57dbd616a550daec7be3fc9e7056e1628d1820c9ba0ac37a71875a8f90007&" alt="hero image" />
      </div>
    </section>
  </body>
</html>

